version: '3'
services:
  pre-install-config:
    # Handle install-time config
    image: alpine
    container_name: pre-config
    volumes: 
      - cfg

  redis:
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"
    networks:
      - backend

  pretix:
    image: pretix/standalone:stable
    container_name: pretix
    depends_on:
      - database
      - redis
    ports:
      - "8000:80"
    volumes:
      - cfg:/etc/pretix/pretix.cfg
      - data:/data
      - src:/pretix/src
    networks:
      - backend
  database:
    image: postgres:9.6
    container_name: database
    #entrypoint: psql -U postgres postgres
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data 
    networks:
      - backend
volumes:
  data:
  pg_data:
  cfg:
  src:

networks:
  backend:
