version: '3'
services:
  database:
    image: postgres:9.6-alpine
    container_name: database
    environment: 
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=pretix
      - POSTGRES_DB=pretix
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - postgres:/var/lib/postgresql/data 
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: cache
    volumes:
      - ./etc/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - backend

  pretix:
    build: .
    container_name: pretix
    depends_on:
      - database
      - redis
    ports:
      - "8000:80"
    volumes:
      - ./etc/pretix.cfg:/etc/pretix/pretix.cfg
      - data:/data
    networks:
      - backend

volumes:
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PWD}/rootfs/data
  postgres:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PWD}/rootfs/postgres

networks:
  backend:
