version: '3'
services:
  database:
    image: postgres:9.6-alpine
    environment: 
      NETWORK_ACCESS=internal
      POSTGRES_USER=pretix
      POSTGRES_PASSWORD=
    volumes:
      - ./rootfs/postgresql/data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    environment: 
      NETWORK_ACCESS=internal
    networks:
      - backend

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro #unix socket for Docker daemon, required for nginx-proxy.
    networks:
      - backend

  pythonapp:
    build: .
    environment:
      - VIRTUAL_HOST=pretix.local
      - PYTHONUNBUFFERED=0
    volumes:
      - ./pretix:/app/pretix
    networks:
      - backend

networks:
  backend:
